services:
  backend:
    build:
      context: ./backend
    container_name: shopverse-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app   # mount local code for hot reload
      - /app/node_modules # keep container's node_modules

  db:
    image: postgres:15
    container_name: shopverse-db
    restart: always
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
      POSTGRES_DB: shopverse
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
